version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - apierrors
  - apiserver
  - cenkalti
  - Factorio
  - gorcon
  - grpcotel
  - grpcpkg
  - healthz
  - httppkg
  - labstack
  - nekomeowww
  - opentelemetry
  - Otel
  - otelgrpc
  - otelhttp
  - protovalidate
  - RCON
  - samber
ignoreWords: []
import: []
